### PR TITLE
Added information for Heater, Thermistor & Heatblock

### PR DESCRIPTION
**Pull request by LimesKey**
After my recent issue #16, I discovered more information about the thermistor and heatblock and wanted to publish it here for everyone to see. I added more information for all 3 parts of the printer and how to order the new parts individually. The thermistor that comes stock has wires which are very easy to break and fragile, leading me to have to buy more.

I also added 2 DIY methods for anyone wanting to either, use a MK8 nozzle or use a Cartridge thermistor instead.

### CODE REVIEW

**Comment by bassamanator** [comment]
Thanks. Will merge.

**Comment by bassamanator** [comment]
@LimesKey Going through this pr, thanks for all your hard work.

Any guesses as to the material of the stock heatblock? From what I remember, it wasn't light enough to be aluminum, and considering that it's rated at 300C, and it's colour, I image it's nickle plated copper?

**Comment by bassamanator** [comment]
No please don't drill it. All information that has not been verified is marked as such, and so will this bit about the material. Thanks.

**Comment by bassamanator** [comment]
@LimesKey I merged (from the command line of course) and pushed, but for some reason this pr wasn't closed, and github is not listing you as a contributor. It's happened before too, but this time maybe because there were a lot of changes.

Can you please catch up to `main` and add [this link](https://s.click.aliexpress.com/e/_DCq3Ym5) as an aftermarket option for the thermistor? Please then create a pr and I'll accept it here in github, so you get credit for all your hard work.

When time permits...

**Comment by LimesKey** [comment]
@bassamanator I already listed a suitable replacement thermistor in the aftermarket options, but I can add yours.
image

I'm very confused with what happened with the merge thing... would it be possible for you to revert the commit and try merging from the website?

Are you able to put the heater cartridge section where it talks about removal and mounting right underneath the level 3 "Heater Cartridge" heading so it's more organized instead of putting it under the thermistor heading. I can do it too though.
image

I'm confused, the heatblocks on AliExpress say "Copper plated" but that doesn't seem right... Maybe it is nickel plated copper.
image


I like the editing of what I wrote though, good job.

**Comment by bassamanator** [comment]
It's still showing a large change. Please pull from main and create a small change, then create a separate PR.

I do not merge from the GitHub editor, it doesn’t provide me with the control that I need. I’m very serious about commits. I start the merge from the command line then make edits in VSCode.

Regarding your heater cartridge information. You're write-ups are good, but they are too generalized to 3d printing. This repo is a spec-sheet first and foremost for this printer. If I could use no words, I would. I want the user to come to this repo, instantly get the information they want, I don't want them to read a paragraph in order to get the information they are after. Sometimes this is unavoidable of course. In any case, that's the user experience I'm trying to create.

I also considered putting the removal of the heater cartridge into an `Advanced` section, however, an advanced user already knows how to remove the heater cartridge: heat and pressure. What will end up happening is that beginners will go into this section, and get second degree burns. Not the experience I’m trying to create, specially considering how cheap a heater cartridge is, and again, this issue pertains more generally to 3D printing. Secondly, I’m trying to circumvent this issue all together by providing the user with cheap alternatives, but that takes time. For example, I received my new heatblock today (third one), and it will fit, and it has holes for a bead thermistor, and the new standard thermistor. What’s delaying me right now is that I don’t have M2.5 countersunk screws that are long enough, and I’m not sure how long they need to be. As soon as I have those screws, I’ll create a bill of materials and right up *exactly* what the user needs to do to switch to a non-Sovol hotend. And lastly, this might not even be an issue any more, because a user just told me today on reddit, how easy it was to remove the heater and thermistor; Sovol might not be gluing things into place anymore, or using simply a thicker thermal paste.

Would it be useful to provide advanced information to the user? Maybe. This repo is still in its infancy, I don’t have a clear idea of what it will look like ultimately.

I think it would be useful if you created a 3d-printing-tips-and-tricks repo, taking about the things you mentioned in your PR, I think there's a market for it. There are sites out there, but we both know how easy things are with Github repos and markdown. Heck I would probably even link to your repo. Alternatively, you can even just keep working on your own fork of this repo, and keep it separate if you like, that’s totally cool.

Anyway, I appreciate all your hard work. Thanks!

**Comment by LimesKey** [comment]
Thanks for your reply, I agree with what you said. What do you think about adding a beginner tutorials/faq folder, a place with more writing and less information-heavy for noobies? A place to put some of the basic maintenance steps like one of the common issues for me was filament getting stuck inbetween the gears when loading filament so I could add the answer to that?

> And lastly, this might not even be an issue any more, because a user just told me today on reddit, how easy it was to remove the heater and thermistor

Maybe because it was a brand new hotend, likely if you have to remove the heater chances are that there's a big blob of filament on it. In my case it was polycarbonate and very difficult to remove.

Would it be possible to contact you on Discord, not a fan of using Github for basic messaging. My handle is LimesKey#0001.

**Comment by bassamanator** [comment]
Request sent on discord.

**Pull request closed without merging**
