### PR TITLE
Options for heater cartridge and thermistor

### PR DESCRIPTION
**Pull request by albertoabrao**
The thermistor and heater cartridge seem to be the same ones used on the Ender 3 S1 (Pro)

### CODE REVIEW

**Comment by bassamanator** [comment]
Incorrect information. 

Everything Ender 3 S1 Pro heater cartridge that I've found on amazon and aliexpress uses XH2.54 2-pin connector.

**Comment by albertoabrao** [comment]
That is true, I just double checked.

The thermistor, however, seem to be a match, other than the wires being slightly bigger. It remains to be seen if they'd work. I will eventually be able to test, and will report back after.

**Comment by bassamanator** [comment]
The thermistor does have the correct connector, however, it is encased inside a 3mm cartridge. The problem is the stock heatblock only has a 2mm hole.

Eventually, I want to let users know that if they've changed their heatblock to one that has 3mm hole for the thermistor, they can use the thermistor that I've found, which I guess is the same as the ender.

**Comment by bassamanator** [comment]
Feel free to contribute again btw, just be careful about the information.

**Comment by Giuseppe499** [comment]
> The thermistor does have the correct connector, however, it is encased inside a 3mm cartridge. The problem is the stock heatblock only has a 2mm hole.
> 
> Eventually, I want to let users know that if they've changed their heatblock to one that has 3mm hole for the thermistor, they can use the thermistor that I've found, which I guess is the same as the ender.

Hi, my stock heatblock has a 3mm hole for the thermistor. I checked with a caliper. Maybe sovol used different heatblocks in different batches of production.

I have bought [this](https://www.aliexpress.com/item/1005005047050454.html?spm=a2g0o.order_list.order_list_main.5.44323696MrkcuV) thermistor to replace the broken one on my sv06. I will update to tell you if it fits

Here are some photos of the measurement that I've taken. The quality isn't good because it is difficult to measure and take photos at the same time 🙃.
IMG20231009112957
IMG20231009113034
IMG20231009113038
IMG20231009113128

**Comment by bassamanator** [comment]
@Giuseppe499 May I ask when you purchased the printer or that hotend? In any case, it's good news because glass bead thermistors with the correct cable length are impossible to find compared 3mm cartridge thermistors which are readily available in the correct length.

**Comment by Giuseppe499** [comment]
@bassamanator I bought the printer from 3DJake 2 weeks ago. The thermistor was broken on arrival and while I'm waiting for a replacement hotend, I bought new thermistors to repair this one

**Comment by Giuseppe499** [comment]
AliExpress is taking too much to ship the thermistors, so I bought this [one](https://www.amazon.it/dp/B0BBBK6XK9?psc=1&ref=ppx_yo2ov_dt_b_product_details) on Amazon and I can confirm that it fits in the stock hotend that came with my SV06.

I did a PID calibration in Klipper and it seems to work.

Here are some photos
photo_2023-10-14_18-09-52
photo_2023-10-14_18-10-06

**Comment by bassamanator** [comment]
@Giuseppe499 Added note about the 3mm thermistor hole to the heatblock section. Thanks!

**Pull request closed without merging**
