### PR TITLE
Added beacon probe setup

### PR DESCRIPTION
**Pull request by 1Euro7Cent**

### CODE REVIEW

**Comment by bassamanator** [comment]
Thanks! Will look into this shortly.

**Comment by DerDreschner** [comment]
Ordered a beacon probe last week. Should be shipped within the next few days. Will follow your instructions and report back as soon as I receive it.

**Comment by 1Euro7Cent** [comment]
i forgot one setting to add to it for a command to work. will change it tomorrow

**Comment by bassamanator** [comment]
Merged this into [mods branch](https://github.com/bassamanator/everything-sovol-sv06/tree/mods). I want to keep the `main` branch for specs mostly. The `mods` branch will hold 'heavy' modifications such as this. Organization is always difficult.

Waiting to close this PR until I can confirm that you've been added as a contributor on this repo. If it doesn't work, then I'll attempt the merge differently. Please keep this PR open and unmodified. Thanks!

**Pull request merged**
