### PR TITLE
edited the readme.md

### PR DESCRIPTION
**Pull request by Eoldev-Terry**
Lead_screws_specs

Rods_specs

### CODE REVIEW

**Comment by bassamanator** [comment]
@Eoldev-Terry This is great Terry, but could you please adjust this to *not* use images? So, it should be a markdown table. You can look at the table that I'm using, and you can also look at this markdown [playground of sorts](https://remarkjs.github.io/react-markdown/), just be sure to enable `Use remark-gfm (to enable GFM)` at the very top.

I could do this myself, however, it won't show up as a `merged pull request` in *your* profile, which is kind of fun.

**Comment by bassamanator** [comment]
Take your time with this. In case if this is too much trouble, I'll write the markdown for you and you can still create a pull request with it.

**Comment by Eoldev-Terry** [comment]
Hi Bassam. It’s not too much trouble. I am just a little busy. However you
want to proceed is fine; it’s your project. I am happy to be learning new
things.

**Comment by Eoldev-Terry** [comment]
Ok, I believe that I have changed the markdown in the pull request

**Comment by bassamanator** [comment]
Merged, thanks!

**Comment by Eoldev-Terry** [comment]
Awesome!  Thanks for your patience.

**Comment by Eoldev-Terry** [comment]
Hi Bassam. Can you correct the X rod length? It should be 355 mm. Sorry I
made a mistake from my notes. If you want me to do a pull request for
it, please let me know.
-Terry

**Pull request merged**
